# Build Gccm in a stock Go builder container
FROM golang:1.15-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /ccmchain
RUN cd /ccmchain && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /ccmchain/build/bin/* /usr/local/bin/

EXPOSE 8545 8546 8547 30303 30303/udp
